if(NOT DEFINED WASI_SDK_DIR)
  message(FATAL_ERROR "WASI_SDK_DIR is not set")
endif()

set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES WASI_SDK_DIR)

set(CMAKE_SYSROOT "${WASI_SDK_DIR}/share/wasi-sysroot")

set(CMAKE_C_COMPILER "${WASI_SDK_DIR}/bin/clang")
set(CMAKE_CXX_COMPILER "${WASI_SDK_DIR}/bin/clang++")
set(CMAKE_AR "${WASI_SDK_DIR}/bin/llvm-ar")
set(CMAKE_RANLIB "${WASI_SDK_DIR}/bin/llvm-ranlib")

set(CMAKE_C_COMPILER_TARGET wasm32-wasi)
set(CMAKE_CXX_COMPILER_TARGET wasm32-wasi)

set(CMAKE_EXECUTABLE_SUFFIX ".wasm")
